<a href="https://colab.research.google.com/github/bcdanl/299-code/blob/main/danl_299_script_2025_1022.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
# Below is for an interactive display of DataFrame in Colab
from google.colab import data_table
data_table.enable_dataframe_formatter()

# CW7


## Part 1

### Q1

In [2]:
ny_pincp = pd.read_csv('https://bcdanl.github.io/data/NY_pinc_wide.csv')
ny_pincp

fips          geoname  pincp1969  pincp1970  pincp1971  pincp1972  \
0   36000         New York       4619       4920       5234       5603   
1   36001       Albany, NY       4272       4821       5304       5709   
2   36003     Allegany, NY       2928       3208       3424       3511   
3   36005        Bronx, NY       3632       3839       3999       4199   
4   36007       Broome, NY       3895       4153       4412       4700   
..    ...              ...        ...        ...        ...        ...   
58  36115   Washington, NY       3102       3385       3535       3746   
59  36117        Wayne, NY       3752       3854       4086       4342   
60  36119  Westchester, NY       6365       6682       7095       7550   
61  36121      Wyoming, NY       3360       3534       3803       4226   
62  36123        Yates, NY       3293       3497       3767       3898   

    pincp1973  pincp1974  pincp1975  pincp1976  ...  pincp2010  pincp2011  \
0        6022       6533       7066       7510  ...      48973      51496   
1        6154       6641       7184       7623  ...      46559      48417   
2        3831       4211       4513       4808  ...      28206      28939   
3        4497       4894       5373       5633  ...      29901      30546   
4        5061       5517       5991       6393  ...      35558      36651   
..        ...        ...        ...        ...  ...        ...        ...   
58       4092       4458       4691       5040  ...      31066      32707   
59       4871       5408       5803       6140  ...      35095      36463   
60       8005       8704       9446      10042  ...      76051      79996   
61       4705       5041       5351       5592  ...      31234      33022   
62       4502       5149       5467       5736  ...      31336      32677   

    pincp2012  pincp2013  pincp2014  pincp2015  pincp2016  pincp2017  \
0       53986      54501      56758      59243      61401      65814   
1       50190      50809      53790      55793      55805      59640   
2       30005      29997      31457      32377      32497      34116   
3       30537      30827      31833      33162      33794      36140   
4       37786      37802      38282      39980      40696      43055   
..        ...        ...        ...        ...        ...        ...   
58      33484      34116      35236      35808      36707      39002   
59      37546      38445      39295      41170      42377      44962   
60      87602      86452      90438      93819      96620     103808   
61      33969      35046      36990      36729      37265      39604   
62      33578      34154      35028      34915      36206      38359   

    pincp2018  pincp2019  
0       68657      71717  
1       60637      63037  
2       34784      36164  
3       37459      39711  
4       44332      46361  
..        ...        ...  
58      40148      42181  
59      45828      47886  
60     109324     113477  
61      40115      43176  
62      38788      40877  

[63 rows x 53 columns]

In [4]:
ny_pincp.columns

Index(['fips', 'geoname', 'pincp1969', 'pincp1970', 'pincp1971', 'pincp1972',
       'pincp1973', 'pincp1974', 'pincp1975', 'pincp1976', 'pincp1977',
       'pincp1978', 'pincp1979', 'pincp1980', 'pincp1981', 'pincp1982',
       'pincp1983', 'pincp1984', 'pincp1985', 'pincp1986', 'pincp1987',
       'pincp1988', 'pincp1989', 'pincp1990', 'pincp1991', 'pincp1992',
       'pincp1993', 'pincp1994', 'pincp1995', 'pincp1996', 'pincp1997',
       'pincp1998', 'pincp1999', 'pincp2000', 'pincp2001', 'pincp2002',
       'pincp2003', 'pincp2004', 'pincp2005', 'pincp2006', 'pincp2007',
       'pincp2008', 'pincp2009', 'pincp2010', 'pincp2011', 'pincp2012',
       'pincp2013', 'pincp2014', 'pincp2015', 'pincp2016', 'pincp2017',
       'pincp2018', 'pincp2019'],
      dtype='object')

In [3]:
(
    ny_pincp
    .melt()
)

variable   value
0          fips   36000
1          fips   36001
2          fips   36003
3          fips   36005
4          fips   36007
...         ...     ...
3334  pincp2019   42181
3335  pincp2019   47886
3336  pincp2019  113477
3337  pincp2019   43176
3338  pincp2019   40877

[3339 rows x 2 columns]

In [7]:
(
    ny_pincp
    .query('fips != 36000')
    .melt(id_vars=['fips', 'geoname'],
          var_name = 'year',
          value_name = 'pincp')
    .sort_values(['fips', 'year'])
)

fips     geoname       year  pincp
0     36001  Albany, NY  pincp1969   4272
62    36001  Albany, NY  pincp1970   4821
124   36001  Albany, NY  pincp1971   5304
186   36001  Albany, NY  pincp1972   5709
248   36001  Albany, NY  pincp1973   6154
...     ...         ...        ...    ...
2913  36123   Yates, NY  pincp2015  34915
2975  36123   Yates, NY  pincp2016  36206
3037  36123   Yates, NY  pincp2017  38359
3099  36123   Yates, NY  pincp2018  38788
3161  36123   Yates, NY  pincp2019  40877

[3162 rows x 4 columns]

### Q2

In [5]:
covid = pd.read_csv('https://bcdanl.github.io/data/covid19_cases.csv')
covid

date     dateRep  day  month  year  cases  deaths  \
0      2019-12-31  31/12/2019   31     12  2019      0       0   
1      2019-12-31  31/12/2019   31     12  2019      0       0   
2      2019-12-31  31/12/2019   31     12  2019      0       0   
3      2019-12-31  31/12/2019   31     12  2019      0       0   
4      2019-12-31  31/12/2019   31     12  2019      0       0   
...           ...         ...  ...    ...   ...    ...     ...   
43713  2020-09-19  19/09/2020   19      9  2020     77       0   
43714  2020-09-19  19/09/2020   19      9  2020   1771      62   
43715  2020-09-19  19/09/2020   19      9  2020     28       0   
43716  2020-09-19  19/09/2020   19      9  2020      0       0   
43717  2020-09-19  19/09/2020   19      9  2020     47       1   

      countriesAndTerritories geoId countryterritoryCode  popData2019  \
0                     Belgium    BE                  BEL   11455519.0   
1                      Mexico    MX                  MEX  127575529.0   
2                     Ecuador    EC                  ECU   17373657.0   
3                      Russia    RU                  RUS  145872260.0   
4                 Netherlands    NL                  NLD   17282163.0   
...                       ...   ...                  ...          ...   
43713                  Guinea    GN                  GIN   12771246.0   
43714                  Turkey    TR                  TUR   82003882.0   
43715           Guinea_Bissau    GW                  GNB    1920917.0   
43716                 Tunisia    TN                  TUN   11694721.0   
43717             Afghanistan    AF                  AFG   38041757.0   

      continentExp  Cumulative_number_for_14_days_of_COVID-19_cases_per_100000  
0           Europe                                                NaN           
1          America                                                NaN           
2          America                                                NaN           
3           Europe                                                NaN           
4           Europe                                                NaN           
...            ...                                                ...           
43713       Africa                                           5.105218           
43714         Asia                                          28.358414           
43715       Africa                                           3.019391           
43716       Africa                                          35.708419           
43717         Asia                                           1.616645           

[43718 rows x 13 columns]

## Part 2

In [8]:
flights = pd.read_csv("https://bcdanl.github.io/data/flights.zip")
airlines = pd.read_csv("https://bcdanl.github.io/data/flights-airlines.csv")
airports = pd.read_csv("https://bcdanl.github.io/data/flights-airports.csv")
planes = pd.read_csv("https://bcdanl.github.io/data/flights-planes.csv")
weather = pd.read_csv("https://bcdanl.github.io/data/flights-weather.csv")

### Q3
Merge the flights and weather DataFrames so that all observations from flights are retained in the resulting DataFrame.



In [9]:
flights.columns

Index(['year', 'month', 'day', 'dep_time', 'sched_dep_time', 'dep_delay',
       'arr_time', 'sched_arr_time', 'arr_delay', 'carrier', 'flight',
       'tailnum', 'origin', 'dest', 'air_time', 'distance', 'hour', 'minute',
       'time_hour'],
      dtype='object')

In [10]:
q3 = (
    flights
    .merge(
        weather,
        on = ['year', 'month', 'day', 'hour', 'origin'],
        how = 'left'
    )
)

q3

year  month  day  dep_time  sched_dep_time  dep_delay  arr_time  \
0       2013      1    1     517.0             515        2.0     830.0   
1       2013      1    1     533.0             529        4.0     850.0   
2       2013      1    1     542.0             540        2.0     923.0   
3       2013      1    1     544.0             545       -1.0    1004.0   
4       2013      1    1     554.0             600       -6.0     812.0   
...      ...    ...  ...       ...             ...        ...       ...   
336771  2013      9   30       NaN            1455        NaN       NaN   
336772  2013      9   30       NaN            2200        NaN       NaN   
336773  2013      9   30       NaN            1210        NaN       NaN   
336774  2013      9   30       NaN            1159        NaN       NaN   
336775  2013      9   30       NaN             840        NaN       NaN   

        sched_arr_time  arr_delay carrier  ...   temp   dewp  humid wind_dir  \
0                  819       11.0      UA  ...  39.02  28.04  64.43    260.0   
1                  830       20.0      UA  ...  39.92  24.98  54.81    250.0   
2                  850       33.0      AA  ...  39.02  26.96  61.63    260.0   
3                 1022      -18.0      B6  ...  39.02  26.96  61.63    260.0   
4                  837      -25.0      DL  ...  39.92  24.98  54.81    260.0   
...                ...        ...     ...  ...    ...    ...    ...      ...   
336771            1634        NaN      9E  ...  68.00  55.04  63.21    190.0   
336772            2312        NaN      9E  ...  64.94  53.06  65.37    200.0   
336773            1330        NaN      MQ  ...  69.08  48.02  46.99     70.0   
336774            1344        NaN      MQ  ...  66.92  48.92  52.35     70.0   
336775            1020        NaN      MQ  ...  60.98  51.08  69.86      NaN   

        wind_speed  wind_gust  precip  pressure visib           time_hour_y  
0         12.65858        NaN     0.0    1011.9  10.0  2013-01-01T10:00:00Z  
1         14.96014   21.86482     0.0    1011.4  10.0  2013-01-01T10:00:00Z  
2         14.96014        NaN     0.0    1012.1  10.0  2013-01-01T10:00:00Z  
3         14.96014        NaN     0.0    1012.1  10.0  2013-01-01T10:00:00Z  
4         16.11092   23.01560     0.0    1011.7  10.0  2013-01-01T11:00:00Z  
...            ...        ...     ...       ...   ...                   ...  
336771    11.50780        NaN     0.0    1016.6  10.0  2013-09-30T18:00:00Z  
336772     6.90468        NaN     0.0    1015.8  10.0  2013-10-01T02:00:00Z  
336773     5.75390        NaN     0.0    1016.7  10.0  2013-09-30T16:00:00Z  
336774     8.05546        NaN     0.0    1017.5  10.0  2013-09-30T15:00:00Z  
336775     5.75390        NaN     0.0    1018.6  10.0  2013-09-30T12:00:00Z  

[336776 rows x 29 columns]

### Q4
Identify the airlines (by full name) that have the top five dep_delay values in the flights DataFrame.



In [14]:
(
    flights
    .nlargest(
        5, 'dep_delay',
        keep = 'all'
    )
    .merge(airlines,
           on = 'carrier',
           how = 'left')
    [['name','dep_delay']]
)

name  dep_delay
0  Hawaiian Airlines Inc.     1301.0
1               Envoy Air     1137.0
2               Envoy Air     1126.0
3  American Airlines Inc.     1014.0
4               Envoy Air     1005.0

### Q5
Consider the following two airlines:

- Delta Air Lines Inc. (DL)
- United Air Lines Inc. (UA)

Determine which airline has a higher proportion of flights with a dep_delay greater than 30 minutes.

In [17]:
import numpy as np

In [22]:
q5 = (
    flights
    .query(
       'carrier.isin(["DL", "UA"])'
    )
    [['dep_delay', 'carrier']]
)

q5['cat'] = np.where(
   q5['dep_delay'] > 30, True, False
)

q5_final = (
    q5[['carrier', 'cat']]
    .value_counts()
    .reset_index()
)

q5_final

carrier    cat  count
0      UA  False  51048
1      DL  False  43128
2      UA   True   7617
3      DL   True   4982

In [36]:
DL_num = q5_final.query('carrier == "DL" & cat == True')['count'].values
DL_denom = q5_final.query('carrier == "DL"')['count'].sum()

In [37]:
DL_num

array([4982])

In [38]:
DL_denom

np.int64(48110)

In [39]:
DL_num / DL_denom

array([0.10355435])

In [41]:
UA_num = q5_final.query('carrier == "UA" & cat == True')['count'].values
UA_denom = q5_final.query('carrier == "UA"')['count'].sum()

In [42]:
UA_num / UA_denom

array([0.12983892])

In [44]:
DL_num / DL_denom < UA_num / UA_denom

array([ True])